"""Slot grid generation from config (FR-10..FR-16).

Pure function of an `EventConfig`: no file I/O happens here, so the grid can
be regenerated by editing `config/event.yaml` alone (CLAUDE.md invariant 5).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta

from iff_scheduler.domain.models import Slot
from iff_scheduler.settings import DayConfig, EventConfig


@dataclass(frozen=True)
class SlotGrid:
    """The generated slots plus any non-fatal warnings (e.g. FR-15 discards)."""

    slots: list[Slot]
    warnings: list[str] = field(default_factory=list)

    def __len__(self) -> int:
        return len(self.slots)


def build_slot_grid(event: EventConfig) -> SlotGrid:
    """Generate the full event slot grid from `event.days` and `interview_duration_minutes`.

    Slots are stepped in fixed `interview_duration_minutes` increments from
    each day's start to its end. A slot that overlaps a configured break
    window is skipped entirely (FR-14). A trailing slot that would run past
    the day's end time is discarded and reported, not truncated (FR-15).
    """
    duration = timedelta(minutes=event.interview_duration_minutes)
    if duration <= timedelta(0):
        raise ValueError("interview_duration_minutes must be positive")

    slots: list[Slot] = []
    warnings: list[str] = []
    slot_index = 0

    for day in event.days:
        day_start = datetime.combine(day.date, day.start)
        day_end = datetime.combine(day.date, day.end)
        if day_end <= day_start:
            raise ValueError(f"{day.date}: end time must be after start time")

        cursor = day_start
        while cursor + duration <= day_end:
            slot_end = cursor + duration
            if not _overlaps_any_break(cursor, slot_end, day):
                slots.append(
                    Slot(
                        slot_id=f"{day.date.isoformat()}_{cursor.time().strftime('%H%M')}",
                        date=day.date,
                        day_label=day.label,
                        start_time=cursor.time(),
                        end_time=slot_end.time(),
                        slot_index=slot_index,
                    )
                )
                slot_index += 1
            cursor = slot_end

        remainder = day_end - cursor
        if timedelta(0) < remainder < duration:
            minutes = int(remainder.total_seconds() // 60)
            warnings.append(
                f"{day.date.isoformat()}: trailing partial slot of {minutes} minute(s) "
                f"discarded (day ends {day.end.isoformat()}, last full slot ends "
                f"{cursor.time().isoformat()})"
            )

    return SlotGrid(slots=slots, warnings=warnings)


def _overlaps_any_break(start: datetime, end: datetime, day: DayConfig) -> bool:
    for brk in day.breaks:
        break_start = datetime.combine(day.date, brk.start)
        break_end = datetime.combine(day.date, brk.end)
        if start < break_end and end > break_start:
            return True
    return False
